### PR TITLE
Allow both precompiled and from source versions

### PR DESCRIPTION
**Pull request by tmasthay**
## Refactor: Move Precompiled Interface Out of Main

The main branch now includes the version compiled from source, as it has the fewest dependencies. The precompiled version is still usable. To use the precompiled version of the package, run the following commands:

```julia
using Pkg
Pkg.add(url=REPO_URL, rev="precompiled")
```

### Usage Options

There are three main ways to use this package:

#### 1. Without Madagascar
- Install the basic package:
  ```
  Pkg.add(REPO_URL)
  ```
- Supports only `rsf_write` and `rsf_read`.

#### 2. With a Local Madagascar Installation
- Install Madagascar:
  ```julia
  Pkg.add("Madagascar")
  ```
- Assumes that Madagascar binaries are in the `RSFROOT` environment variable.

#### 3. With Precompiled Binaries
- Install using precompiled binaries:
  ```julia
  Pkg.add(url=REPO_URL, rev="precompiled")
  ```
- This is the most convenient way to use the package but the least flexible.

The decision behind this refactor is because maintenance of the precompiled binaries is harder and the pre-existing build system of Madagascar is already robust. Furthermore, this allows the package to be used in a more flexible way by allowing devs to use their own Madagascar binaries if they want.

## TODO
I believe it is possible to lump this all into one command; however, I had trouble with this. Looks something like
```julia
using Requires
const precompile_possible = Sys.islinux() && Sys.isx86
const force_from_source = get(ENV, RSF_FORCE_JULIA_SOURCE, "0") == "1"
global jll_avail = false
@requires Madagascar_jll = JLL_UUID global jll_avail = true
const do_precompilation = precompile_possible && !force_from_source && jll_avail
if do_precompilation
    include("precompiled.jl")
else 
    include("from_source.jl")
end
```

The trouble with the above ultimately comes from `Project.toml.` I tried putting Madagascar_jll as an extra dependency rather than a required one, but then things were breaking local `Pkg.add("Madagascar")` tests. This is why I moved towards just putting them in separate branches for now. What might be simplest too is that until we have a precompiled binary for Mac OSX, to somehow make `Madagascar_jll` still installable by having it evaluate to `nothing` or something like this, give a message to Mac users and then simply force a build from source.

### CODE REVIEW

**Comment by mloubout** [comment]
>The main branch now includes the version compiled from sources, as it has the fewest dependencies. The precompiled version is still usable

That goes against the whole point of how julia handles binaries and libraries, the `jll` should always be the default (main) behaviour with an option to use user/system libraries if wanted. 

For the best way to do it, I would recommend to look at `CUDA.jl` and in particular [CUDA_Runtime_Discovery.jl](https://github.com/JuliaGPU/CUDA_Runtime_Discovery.jl) for ways to handle switching between `jll` and system libraries. But a separate branch is not optimal.

**Comment by tmasthay** [comment]
Okay, yes it looks like `CUDA.jl` imports `CUDA_Runtime_jll`. I tried something similar to `CUDA.jl`, but the main issue I have is the lack of a macOS tarball, which causes an immediate crash of `Pkg.add("Madagascar")`.

Is the only way to rectify this to ultimately fix your previous pull request for `Yggdrasil` or is there a way to allow `Pkg.add("Madagascar_jll")` to just give a warning that the tarballs were not found? If all I get is a warning, then I can do logic in `Madagascar.jl` that basically says 
```
if Sys.islinux()
    include("precompiled.jl")
else
    include("from_source.jl")
end
```

I still have not been able to fix that pull request, which is why I aimed at, in the short term, getting a "from source" fallback.

**Comment by mloubout** [comment]
I think fixing that PR.to have proper jll for osx is the main thing, I was having issues for windows but can probably slip.it for now. I've put a reminder to have a look this weel

**Comment by mloubout** [comment]
So after spending a lot of time on it, there is still quite a few place (especially in `user/`) that are not compiling correctly with arm clang so it makes the debug a bit of a pain. I have some patch but started to hit places like `src/user/jeff/wem2d_iso_kernel.c` that need almost complete rewrite for proper rsf complex which I don't have time for.

So I am not sure what the best way to go but the lack of homogeneity in some of those libraries make it quite a pain and I don't know how much time I can spend on it.

**Comment by tmasthay** [comment]
Okay, no worries thank you for spending time working on it. I've spent time on it too and can't get it to work on mac. In the meantime, I will just point people to the fork of my repo that does not use `Madagascar_jll` at all and just assumes a build from source. I will make a close this pull request and make a new one if I figure out the mac precompiled binaries since, like you said, two divergent branches as a solution is not ideal.

**Pull request closed without merging**
